name: Run plugin tests
on: [push, pull_request]
jobs:
  phpcs:
    runs-on: ubuntu-latest
    name: Check WP Coding Standards
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: none
          tools: phpcs

      - name: Setup PHPCS for WordPress
        run: |
          composer global require phpcompatibility/phpcompatibility-wp
          composer global require wp-coding-standards/wpcs
          composer global require automattic/vipwpcs
          composer global require dealerdirect/phpcodesniffer-composer-installer

      - name: Run PHPCS on the plugin
        run: phpcs

